name: Feature
description: Add a new feature
labels: ["type: feature"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Feature description
    validations:
      required: false
