name: Bug Report
description: File a bug report
title: "bugfix/"
labels: ["type: bug"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
