name: Hotfix Report
description: File a Hotfix report
title: "hotfix: "
labels: ["type: hotfix"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Hotfix description
    validations:
      required: true
