name: Release
description: Add a release
title: "/release"
labels: ["type: release"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Release description
    validations:
      required: true
