name: Docs
description: Add docs
title: "docs/"
labels: ["type: documentation"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Documentation description
    validations:
      required: true
