name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
