name: Story
description: Add a story
title: "[Story]: "
labels: ["story"]
projects: ["ftdigital/2"]
assignees:
  - freektimmer
body:
  - type: textarea
    id: description
    wysiwyg: true,
    attributes:
      label: Description
      placeholder: Story description
      render: markdown
    validations:
      required: true
